### ISSUE TITLE
Hanging on CLI after quittting ImageJ Legacy and napari

### ISSUE THREAD

**Issue by gselzer** [imagej/napari-imagej#141] opened 2022-11-18 21:21 UTC
I can reproduce with this 7-step sequence.
* Boot napari-imagej
* Open the ImageJ legacy UI
* Transfer some data from napari to ImageJ
* Auto Threshold that data (Ctrl + Shift + T, Apply, close the window)
* Create Mask from the threshold (search "Create Mask" in the searchbar, run it)
* Transfer the mask back to napari
* Click the close button on napari

Once this happens, I have to use Ctrl+Z and `kill %1` to stop the process.

**Comment by hinerm** [comment] 2023-03-23 19:08
OK this is actually different. The steps are:

1.    Boot napari-imagej
 1.   Open the ImageJ legacy UI
1.    Transfer some data from napari to ImageJ
1.    Auto Threshold that data (Ctrl + Shift + T, click Apply)
1. Click OK
1. Close the threshold window
 1.   Transfer the mask back to napari
 1.   Click the close button on napari

When I run `create Mask` via the search, it does some processing and then the transfer back to napari is very quick. When I do things this way it seems to do some processing at the time of transfer.

**Comment by hinerm** [comment] 2023-03-23 19:22
> Click OK

Note that this only comes up if you have >2D data. However, I was able to reproduce the issue even with 2D (`bricks` napari sample image). @gselzer was not able to reproduce in his environment.

**Comment by hinerm** [comment] 2023-03-24 16:31
@gselzer OK I was wrong.. previously I had "Close the threshold window" in the steps, because I had copy and pasted it. 🏆 

In fact, if you close the threshold window, *closing napari doesn't cause anything to hang*. If you leave the threshold window open, it hangs! 🌈 

Here's a [thread dump](https://gist.github.com/hinerm/dc36733d3e454f47554502be756cd876) 🎁

**Comment by gselzer** [comment] 2023-03-24 18:54
> @gselzer OK I was wrong.. previously I had "Close the threshold window" in the steps, because I had copy and pasted it. 🏆
> 
> In fact, if you close the threshold window, _closing napari doesn't cause anything to hang_. If you leave the threshold window open, it hangs! 🌈
> 
> Here's a [thread dump](https://gist.github.com/hinerm/dc36733d3e454f47554502be756cd876) 🎁

Aha, *now* I can reproduce.

**Closed** 2023-05-03 00:23 UTC
Labels: bug
