### ISSUE TITLE
Type matching issue for detecting available images

### ISSUE THREAD

**Issue by kephale** [imagej/napari-imagej#212] opened 2023-05-09 16:09 UTC
Testing this endpoint: `net.imagej:imagej:2.11.0+org.bonej:bonej-ops:7.0.16+org.bonej:bonej-plugins:7.0.16`

Steps to replicate:
- start napari-imagej with the above endpoint
- in napari: File > Open samples > napari builtin > Binary blobs (3D)
- try to run `Fractal dimension` Command from [BoneJ2](https://github.com/bonej-org/BoneJ2)

The inputImage is not properly detected:

<img width="1438" alt="image" src="https://github.com/imagej/napari-imagej/assets/400105/0ee0da61-057b-4fad-84d3-d89da0f8a9ae">

BoneJ2's Fractal dimension is typed on a RealType, so I'd think a Python bool should be coercable since ImgLib2's BoolType inherits from RealType.

**Comment by ctrueden** [comment] 2023-05-09 22:07
@kephale It is soo cool to see what you're testing. Even when it doesn't work yet. :laughing: 

Just wanted to note that the PyImageJ / napari-imagej support for boolean image conversion is a very recent addition; it required #167 and imagej/pyimagej/pull/252 and imglib/imglyb#19 and imglib/imglib2-imglyb#10 and imglib/imglib2-unsafe#8. (Hooray for modular libraries... :sweat_smile:) So, your endpoint will need imglib2-imglyb 1.1.0 and imglib2-unsafe 1.0.0 in the mix.

We are just now adding logic to napari-imagej to ensure it ships with a reproducible endpoint including the needed versions of stuff on the Java side, so my guess is that the issue here is simply too-old versions of 1 or more Java components, and possibly also 1 or more too-old Python components (pyimagej, imglyb).

**Comment by kephale** [comment] 2023-05-10 10:48
One issue that I just noticed when testing the new endpoints is that if I select that `   `, blank option for inputImage, then it still proceeds to appear as if the Command is being executed:
<img width="814" alt="image" src="https://github.com/imagej/napari-imagej/assets/400105/ca2b3700-e550-487e-8745-12d9f221bca1">

**Comment by gselzer** [comment] 2023-05-10 15:32
> One issue that I just noticed when testing the new endpoints is that if I select that ` `, blank option for inputImage, then it still proceeds to appear as if the Command is being executed: <img alt="image" width="814" src="https://user-images.githubusercontent.com/400105/237365814-ca2b3700-e550-487e-8745-12d9f221bca1.png">

@kephale this is likely because the `Module` is throwing an error? If so, we are currently unable to capture that error and do cleanup (which is why the progress bar remains). But we just merged scijava/scijava-common#459, which will enable us to do that cleanup. I just filed #214 which should fix this.

**Comment by kephale** [comment] 2023-05-11 19:38
For completeness the output of the Fractal Dimension call:

<img width="505" alt="image" src="https://github.com/imagej/napari-imagej/assets/400105/7beda261-26ce-4c95-9a8e-be902c5e196f">

**Closed** 2023-05-11 19:41 UTC
