### ISSUE TITLE
Clearing search leaves leftovers

### ISSUE THREAD

**Issue by hinerm** [imagej/napari-imagej#180] opened 2023-03-06 20:13 UTC
For some reason there are `Script Templates` hits that are leftover after clearing the search bar. They are not present when first starting the plugin:

Before search:
![image](https://user-images.githubusercontent.com/1123809/223220138-99d6328a-58ac-41b5-bbf9-20e2dcc27e46.png)

After search and clear:
![image](https://user-images.githubusercontent.com/1123809/223219995-471dd5f3-1b55-483f-8a34-d0bb96bc11b4.png)

**Comment by ctrueden** [comment] 2023-03-06 20:23
Duplicate of #113.

**Closed by ctrueden** 2023-03-06 20:23 UTC
